### ISSUE TITLE
mocha: command not found

### ISSUE THREAD

**Issue by alexi-o** [den-materials/js-building-iterators-lab#1]
https://superuser.com/questions/260925/how-can-i-make-chown-work-recursively
https://docs.npmjs.com/getting-started/fixing-npm-permissions

After 'npm install' and 'npm install -g mocha', I can't run mocha. Yields 'command not found.'

Seems to be a permissions issues? 
Not sure if this is relevant:
![screen shot 2017-03-20 at 4 17 31 pm](https://cloud.githubusercontent.com/assets/25968667/24124329/c9b650c4-0d88-11e7-879b-3f270ef28fa5.png)

**Comment by ZebGirouard** [comment]
This was a combination of permissions issue (needed to open up node and npm folders) and a bad node/npm install.  After `chown`ing a couple folders and reinstalling `node` with Homebrew, we resolved it.
